# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarminator < Formula
  desc "Go-based swarm node runner with deterministic safety rules and ACP-backed multi-agent execution"
  homepage "https://github.com/InNoobWeTrust/swarminator"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.2.0/swarminator_darwin_amd64.tar.gz"
      sha256 "27db50fb53123b6920ab16e4e5faa7a4c10fbf98b9e0199e3ce11edb4c68eefe"

      define_method(:install) do
        bin.install "swarminator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.2.0/swarminator_darwin_arm64.tar.gz"
      sha256 "6c92a92a3e9fab9ea7bc6c9f2163df1c281fdc68c9a5ab493196799b9f810aa0"

      define_method(:install) do
        bin.install "swarminator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.2.0/swarminator_linux_amd64.tar.gz"
      sha256 "44c029ac818fbb41c9ab4e4afdab4fc0c017f1b7b8276390e9fbbf71dcd39cb7"
      define_method(:install) do
        bin.install "swarminator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.2.0/swarminator_linux_arm64.tar.gz"
      sha256 "b24f9977d33b885120db050252369bb940356ad58abdcae5696921e746ce5d78"
      define_method(:install) do
        bin.install "swarminator"
      end
    end
  end

  test do
    system "#{bin}/swarminator", "--help"
  end
end
