# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarminator < Formula
  desc "Go-based swarm node runner with deterministic safety rules and ACP-backed multi-agent execution"
  homepage "https://github.com/InNoobWeTrust/swarminator"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.5.0/swarminator_darwin_amd64.tar.gz"
      sha256 "a8452b4709522cb3ec45fd8e3d992c94d6985485a59b59fe44c2875033645090"

      define_method(:install) do
        bin.install "swarminator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.5.0/swarminator_darwin_arm64.tar.gz"
      sha256 "ebd1a23287dbd61179de12952500c527108da407664039496bfa7060e2e43334"

      define_method(:install) do
        bin.install "swarminator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.5.0/swarminator_linux_amd64.tar.gz"
      sha256 "34620faa819d83398cc23241fb265e33a28bceb6c7bf68faf5632bcfe8426eae"
      define_method(:install) do
        bin.install "swarminator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/InNoobWeTrust/swarminator/releases/download/v0.5.0/swarminator_linux_arm64.tar.gz"
      sha256 "9e4a295d2c3c0025862033cc1f4749a9c6d19cf6e613d5bea43d8099c3869ae4"
      define_method(:install) do
        bin.install "swarminator"
      end
    end
  end

  test do
    system "#{bin}/swarminator", "--help"
  end
end
